USE `invoice`;

CREATE TABLE `user` (
                        `id` int(11) NOT NULL AUTO_INCREMENT,
                        `mobile` bigint(20) NOT NULL,
                        `password` varchar(255) DEFAULT NULL,
                        `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                        `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                        `email` varchar(125) NOT NULL,
                        `name` varchar(127) DEFAULT NULL,
                        `company_name` varchar(45) DEFAULT NULL,
                        `company_website` varchar(245) DEFAULT NULL,
                        `auth_token` text,
                        `expiry_time` datetime DEFAULT NULL,
                        `company_address` varchar(255) NOT NULL,
                        `organization_id` varchar(99) NOT NULL,
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `uq_mobile` (`mobile`),
                        UNIQUE KEY `uq_email` (`email`),
                        UNIQUE KEY `organization_id` (`organization_id`),
                        KEY `ix_user_created_on` (`created_on`),
                        KEY `ix_user_id` (`id`),
                        KEY `ix_organization_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=79 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `unit` (
                             `id` int(11) NOT NULL AUTO_INCREMENT,
                             `unit_id` varchar(45) NOT NULL,
                             `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                             `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                             `unit` varchar(45) NOT NULL,
                             `unit_name` varchar(45),
                             PRIMARY KEY (`id`),
                             UNIQUE KEY `uq_unit_id` (`unit_id`),
                             UNIQUE KEY `uq_unit` (`unit`),
                             KEY `ix_unit_created_on` (`created_on`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `item` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `item_id` varchar(45) NOT NULL,
                           `name` varchar(45) NOT NULL,
                           `rate` decimal(6,2) NOT NULL,
                           `item_type` varchar(45) NOT NULL,
                           `product_type` varchar(45) NOT NULL,
                           `description` varchar(255) DEFAULT NULL,
                           `sku` varchar(99) DEFAULT NULL COMMENT 'Stock Keeping Unit Number',
                           `organization_id` varchar(99) NOT NULL,
                           `unit_id` varchar(45) DEFAULT NULL,
                           `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `tax_id` varchar(45) DEFAULT NULL,
                           `tax_exemption_id` varchar(45) DEFAULT NULL,
                           `tax_type` varchar(45) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_item_id` (`item_id`),
                           KEY `idx_sku` (`sku`),
                           KEY `fk_organization_id_idx` (`organization_id`),
                           CONSTRAINT `fk_item_unit_id` FOREIGN KEY (`unit_id`) REFERENCES `unit` (`unit_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
                           CONSTRAINT `fk_item_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customer` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
                           `name` varchar(45) DEFAULT NULL,
						   `display_name` varchar(45) NOT NULL,
                           `type` varchar(45) NOT NULL,
                           `company_name` varchar(45) DEFAULT NULL,
                           `website` varchar(255) DEFAULT NULL,
                           `contact` varchar(99) DEFAULT NULL,
                           `email` varchar(99) DEFAULT NULL,
                           `gst_no` varchar(45) DEFAULT NULL,
                           `pan_no` varchar(45) DEFAULT NULL,
                           `payment_terms` int(11) DEFAULT NULL,
                           `payment_label` varchar(45) DEFAULT NULL,
                           `currency` varchar(45) DEFAULT NULL,
                           `notes` varchar(45) DEFAULT NULL,
                           `organization_id` varchar(99) NOT NULL,
                           `tax_id` varchar(45) DEFAULT NULL,
                           `tax_exemption_id` varchar(45) DEFAULT NULL,
                           `tds_tax_id` varchar(45) DEFAULT NULL,
                           `gst_treatment` varchar(45) DEFAULT NULL,
                           `tax_treatment` varchar(45) DEFAULT NULL,
                           `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `updated_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_customer_id` (`customer_id`),
                           KEY `fk_organization_id_idx` (`organization_id`),
                           CONSTRAINT `fk_customer_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `customer_address` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
                           `address_id` varchar(45) NOT NULL,
                           `address_type` varchar(45) DEFAULT NULL,
						   `attention` varchar(45) DEFAULT NULL,
                           `address_line1` varchar(45) DEFAULT NULL,
                           `address_line2` varchar(45) DEFAULT NULL,
                           `city` varchar(255) DEFAULT NULL,
                           `state` varchar(99) DEFAULT NULL,
                           `zip_code` varchar(99) DEFAULT NULL,
                           `contact` varchar(45) DEFAULT NULL,
                           `fax` varchar(45) DEFAULT NULL,
                           `email` varchar(45) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_address_id` (`address_id`),
                           KEY `idx_customer_id` (`customer_id`),
                           KEY `idx_address_id` (`address_id`),
                           CONSTRAINT `fk_address_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `contact_person` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
                           `contact_id` varchar(45) NOT NULL,
						   `name` varchar(45) DEFAULT NULL,
                           `contact` varchar(45) DEFAULT NULL,
                           `email` varchar(45) DEFAULT NULL,
                           `designation` varchar(255) DEFAULT NULL,
                           `department` varchar(255) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_contact_id` (`contact_id`),
                           KEY `idx_customer_id` (`customer_id`),
                           KEY `idx_contact_id` (`contact_id`),
                           CONSTRAINT `fk_contact_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tax` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `tax_id` varchar(45) NOT NULL,
                           `section` varchar(45) NOT NULL,
						   `name` varchar(45) NOT NULL,
                           `percentage` decimal(4,2) NOT NULL,
                           `type` varchar(45) NOT NULL,
                           `start_date` timestamp DEFAULT NULL,
                           `end_date` timestamp DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_tax_id` (`tax_id`),
                           KEY `idx_tax_id` (`tax_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
                           `invoice_id` varchar(45) NOT NULL,
						   `project_id` varchar(45) NOT NULL,
                           `reference_id` varchar(45) DEFAULT NULL,
                           `payment_terms` varchar(45) NOT NULL,
                           `payment_terms_label` varchar(45) NOT NULL,
                           `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `invoice_date` timestamp NOT NULL,
                           `due_date` timestamp DEFAULT NULL,
                           `notes` varchar(45) DEFAULT NULL,
                           `terms` varchar(45) DEFAULT NULL,
                           `subject` varchar(45) DEFAULT NULL,
                           `sub_total` decimal(6,2) NOT NULL,
                           `discount` decimal(6,2) NOT NULL,
                           `discount_type` varchar(45) NOT NULL,
                           `adjustment` decimal(6,2) NOT NULL,
                           `tax_id` varchar(45) DEFAULT NULL,
                           `total` decimal(6,2) NOT NULL,
                           `allow_partial_payment` boolean DEFAULT true,
                           `shipping_charge` decimal(6,2) DEFAULT NULL,
                           `payment_status` varchar(45) DEFAULT NULL,
                           `organization_id` varchar(99) NOT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_project_id` (`project_id`),
                           KEY `idx_invoice_id` (`invoice_id`),
                           KEY `idx_customer_id` (`customer_id`),
                           KEY `idx_organization_id` (`organization_id`),
                           CONSTRAINT `fk_invoice_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
                           CONSTRAINT `fk_invoice_tax_id` FOREIGN KEY (`tax_id`) REFERENCES `tax` (`tax_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
                           CONSTRAINT `fk_invoice_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `invoice_item` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `invoice_id` varchar(45) NOT NULL,
						   `item_id` varchar(45) NOT NULL,
                           `item_order` int(11) NOT NULL,
                           `line_item_id` varchar(45) NOT NULL,
                           `rate` decimal(6,2) NOT NULL,
                           `quantity` decimal(6,2) NOT NULL,
                           `amount` decimal(6,2) NOT NULL,
                           `discount` decimal(6,2) DEFAULT NULL,
                           `description` varchar(45) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_line_item_id` (`line_item_id`),
                           KEY `idx_invoice_id` (`invoice_id`),
                           KEY `idx_item_id` (`item_id`),
                           CONSTRAINT `fk_item_invoice_id` FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`project_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
                           CONSTRAINT `fk_invoice_item_id` FOREIGN KEY (`item_id`) REFERENCES `item` (`item_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `recurring_invoice` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `invoice_id` varchar(45) NOT NULL,
						   `recurrance_id` varchar(45) NOT NULL,
                           `repeat_every` int(11) NOT NULL,
                           `recurrance_frequency` varchar(45) NOT NULL,
                           `recurrance_name` varchar(45) NOT NULL,
                           `recurrance_start` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `recurrance_end` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `total` decimal(6,2) NOT NULL,
                           `recurrance_count` int(11) DEFAULT NULL,
                           `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `status` varchar(45) NOT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_recurrance_id` (`recurrance_id`),
                           KEY `idx_invoice_id` (`invoice_id`),
                           CONSTRAINT `fk_recurrance_invoice_id` FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`project_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `credit_notes` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
						   `credit_notes_id` varchar(45) NOT NULL,
                           `project_id` varchar(45) NOT NULL,
                           `reference_no` varchar(45) DEFAULT NULL,
                           `notes` varchar(45) DEFAULT NULL,
                           `subject` varchar(45) DEFAULT NULL,
                           `terms` varchar(45) DEFAULT NULL,
                           `discount_type` varchar(45) DEFAULT NULL,
                           `discount` decimal(6,2) DEFAULT NULL,
                           `sub_total` decimal(6,2) DEFAULT NULL,
                           `total` decimal(6,2) DEFAULT NULL,
                           `balance` decimal(6,2) DEFAULT NULL,
                           `tax_id` varchar(45) DEFAULT NULL,
                           `adjustment` decimal(6,2) DEFAULT NULL,
                           `date` timestamp DEFAULT NULL,
                           `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `status` varchar(45) DEFAULT NULL,
                           `organization_id` varchar(99) NOT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_project_id` (`project_id`),
                           KEY `idx_credit_notes_id` (`credit_notes_id`),
                           KEY `idx_customer_id` (`customer_id`),
                           CONSTRAINT `fk_credit_notes_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
                           CONSTRAINT `fk_credit_notes_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `credit_notes_item` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `credit_notes_id` varchar(45) NOT NULL,
						   `item_id` varchar(45) NOT NULL,
                           `item_order` int(11) NOT NULL,
                           `line_item_id` varchar(45) NOT NULL,
                           `rate` decimal(6,2) NOT NULL,
                           `quantity` decimal(6,2) NOT NULL,
                           `amount` decimal(6,2) NOT NULL,
                           `discount` decimal(6,2) DEFAULT NULL,
                           `description` varchar(45) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_line_item_id` (`line_item_id`),
                           KEY `idx_credit_notes_id` (`credit_notes_id`),
                           KEY `idx_item_id` (`item_id`),
                           CONSTRAINT `fk_item_credit_notes_id` FOREIGN KEY (`credit_notes_id`) REFERENCES `credit_notes` (`project_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
                           CONSTRAINT `fk_credit_notes_item_id` FOREIGN KEY (`item_id`) REFERENCES `item` (`item_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `estimates` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `customer_id` varchar(45) NOT NULL,
						   `estimate_id` varchar(45) NOT NULL,
                           `project_id` varchar(45) NOT NULL,
                           `reference_no` varchar(45) DEFAULT NULL,
                           `notes` varchar(45) DEFAULT NULL,
                           `subject` varchar(45) DEFAULT NULL,
                           `terms` varchar(45) DEFAULT NULL,
                           `discount_type` varchar(45) DEFAULT NULL,
                           `discount` decimal(6,2) DEFAULT NULL,
                           `sub_total` decimal(6,2) DEFAULT NULL,
                           `total` decimal(6,2) DEFAULT NULL,
                           `balance` decimal(6,2) DEFAULT NULL,
                           `tax_id` varchar(45) DEFAULT NULL,
                           `adjustment` decimal(6,2) DEFAULT NULL,
                           `date` timestamp DEFAULT NULL,
                           `created_on` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `status` varchar(45) DEFAULT NULL,
                           `organization_id` varchar(99) NOT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_project_id` (`project_id`),
                           KEY `idx_estimate_id` (`estimate_id`),
                           KEY `idx_customer_id` (`customer_id`),
                           CONSTRAINT `fk_estimate_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
                           CONSTRAINT `fk_estimate_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `estimate_item` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `estimate_id` varchar(45) NOT NULL,
						   `item_id` varchar(45) NOT NULL,
                           `item_order` int(11) NOT NULL,
                           `line_item_id` varchar(45) NOT NULL,
                           `rate` decimal(6,2) NOT NULL,
                           `quantity` decimal(6,2) NOT NULL,
                           `amount` decimal(6,2) NOT NULL,
                           `discount` decimal(6,2) DEFAULT NULL,
                           `description` varchar(45) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_line_item_id` (`line_item_id`),
                           KEY `idx_estimate_id` (`estimate_id`),
                           KEY `idx_item_id` (`item_id`),
                           CONSTRAINT `fk_item_estimate_id` FOREIGN KEY (`estimate_id`) REFERENCES `estimates` (`project_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
                           CONSTRAINT `fk_estimate_item_id` FOREIGN KEY (`item_id`) REFERENCES `item` (`item_id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `payment_id` varchar(45) NOT NULL,
						   `customer_id` varchar(45) NOT NULL,
                           `payment_mode` varchar(45) NOT NULL,
                           `description` varchar(45) DEFAULT NULL,
                           `date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
                           `payment_date` timestamp NOT NULL,
                           `reference_id` varchar(45) DEFAULT NULL,
                           `amount` decimal(6,2) NOT NULL,
                           `organization_id` varchar(45) NOT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_payment_id` (`payment_id`),
                           CONSTRAINT `fk_payment_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
                           CONSTRAINT `fk_payment_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `user` (`organization_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `payment_invoice` (
                           `id` int(11) NOT NULL AUTO_INCREMENT,
                           `payment_id` varchar(45) NOT NULL,
                           `payment_invoice_id` varchar(45) NOT NULL,
                           `invoice_id` varchar(45) NOT NULL,
                           `amount` decimal(6,2) NOT NULL,
                           `tax_amount` decimal(6,2) DEFAULT NULL,
                           `bank_charge` decimal(6,2) DEFAULT NULL,
                           PRIMARY KEY (`id`),
                           UNIQUE KEY `uq_payment_invoice_id` (`payment_invoice_id`),
                           CONSTRAINT `fk_payment_invoice_id` FOREIGN KEY (`invoice_id`) REFERENCES `invoice` (`project_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
                           CONSTRAINT `fk_payment_payment_id` FOREIGN KEY (`payment_id`) REFERENCES `payment` (`payment_id`) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

